baseURL = 'http://turbo.martyuk.com/'
languageCode = 'ru-RU'
title = 'турбокреатив'
theme = 'no-style'
description = 'начни делать лучшие проекты в своей карьере'

[params.meta]
  author = 'Петр Мартюк'
  favicon = false

[imaging]
  hint = 'photo'
  quality = 75
  resampleFilter = 'box'


