baseURL = 'http://martyuk.com/'
theme = 'no-style'

defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = true
[languages]
  [languages.ru]
    contentDir = 'content/ru'
    disabled = false
    languageCode = 'ru-RU'
    languageDirection = 'ltr'
    languageName = 'Russian'
    title = 'Петр Мартюк'
    weight = 1
    author = 'Петр Мартюк'
  [languages.en]
    contentDir = 'content/en'
    disabled = false
    languageCode = 'en-US'
    languageDirection = 'ltr'
    languageName = 'English'
    title = 'Petr Martyuk'
    weight = 2
    author = 'Petr Martyuk'

[imaging]
  hint = 'photo'
  quality = 75
  resampleFilter = 'box'