baseURL = 'http://turbo.martyuk.com/'
languageCode = 'ru-RU'
title = 'турбокреативный турбоинкубатор'
theme = 'no-style'
description = 'начните создавать лучшие проекты в своей карьере'

[params.meta]
  author = 'Петр Мартюк'

[imaging]
  hint = 'photo'
  quality = 75
  resampleFilter = 'box'


