baseURL = 'http://learn.martyuk.com/'
languageCode = 'ru-RU'
title = 'а название-то и не придумал'
theme = 'no-style'
description = 'курс креативщика'

[params]
  author = 'Петр Мартюк'
  footer = 'kek'

[imaging]
  hint = 'photo'
  quality = 75
  resampleFilter = 'box'


